defmodule HackflareWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hackflare

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_hackflare_key",
    signing_salt: "B7BiQvXN",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Normalize trailing slash form so `/docs/` resolves consistently in prod and dev.
  plug :redirect_docs_trailing_slash

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hackflare,
    gzip: not code_reloading?,
    only: HackflareWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Serve packaged ExDoc HTML from `priv/static/docs` at `/docs` in releases.
  plug Plug.Static,
    at: "/docs",
    from: {__MODULE__, :docs_dir, []},
    gzip: not code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    # In development only, serve generated ExDoc HTML from the project's `doc/` folder.
    plug Plug.Static,
      at: "/docs",
      from: Path.expand("../../doc", __DIR__),
      gzip: false
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug HackflareWeb.Router

  def docs_dir do
    release_docs = Application.app_dir(:hackflare, "priv/static/docs")
    fallback_docs = System.get_env("HACKFLARE_DOCS_DIR", "/app/doc")

    cond do
      File.dir?(release_docs) -> release_docs
      File.dir?(fallback_docs) -> fallback_docs
      true -> release_docs
    end
  end

  defp redirect_docs_trailing_slash(%Plug.Conn{request_path: "/docs/"} = conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("location", "/docs/index.html")
    |> Plug.Conn.send_resp(302, "")
    |> Plug.Conn.halt()
  end

  defp redirect_docs_trailing_slash(conn, _opts), do: conn
end
