frontend:
  - changed-files:
      - any-glob-to-any-file: frontend/**/*

backend:
  - changed-files:
      - any-glob-to-any-file: hackflare_api/**/*

dns:
  - changed-files:
      - any-glob-to-any-file: hackflare_dns/**/*

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**/*

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - Cargo.lock
          - Cargo.toml
          - frontend/package-lock.json
          - frontend/package.json
