services:
  db:
    image: postgres:18.3
    environment:
      POSTGRES_USER: hackflare
      POSTGRES_PASSWORD: hackflare
      POSTGRES_DB: hackflare
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    restart: unless-stopped
  web:
    image: ghcr.io/seradedstripes/hackflare:latest
    depends_on:
      - db
    environment:
      PHX_SERVER: "true"
      MIX_ENV: "prod"
      PORT: "4000"
      SECRET_KEY_BASE: "Sx/6AL8gOMUfxLVU78lnIqghTEOe9pefhaGIOFVP3NYtBBvhFq+Yc46XFs9/3FBt"
    ports:
      - "4000:4000"
      - "53:53/udp"
    restart: unless-stopped

volumes:
  db_data:
