services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: hackflare
      POSTGRES_PASSWORD: hackflare
      POSTGRES_DB: hackflare
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hackflare -d hackflare"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  hackflare:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=./.docker-cache
      cache_to:
        - type=local,dest=./.docker-cache,mode=max
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PHX_SERVER: "true"
      MIX_ENV: "prod"
      PORT: "4000"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "hackflare"
      DB_PASS: "hackflare"
      DB_NAME: "hackflare"
      SECRET_KEY_BASE: "Sx/6AL8gOMUfxLVU78lnIqghTEOe9pefhaGIOFVP3NYtBBvhFq+Yc46XFs9/3FBt"
    ports:
      - "4000:4000"
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped

volumes:
  db_data: