// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dash": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dash";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dash.tsx": {
    id: "routes/dash";
    page: "/dash";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/home": typeof import("./app/routes/home.js");
  "routes/dash": typeof import("./app/routes/dash.js");
};