name: Check Rust Code

on:
  push:
    branches: [ "main" ]
    paths: "native/**"
  workflow_dispatch:

concurrency:
  group: build-and-push
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Caching
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Rust checks
        run: cd native/core && cargo check --all

      - name: Run Rust clippy
        run: cd native/core && cargo clippy --all -- -D warnings