name: Check Rust Code

on:
  push:
    branches: [ "main" ]
    paths: "native/**"
  pull_request:
    branches: ["main"]
    paths: "native/**"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: rust-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust

      - name: Check Crates
        run: cargo check

      - name: Clippy Crates
        run: cargo clippy -- -D warnings
        